### PR TITLE
add features password login & sentinel login.

### PR DESCRIPTION
**Pull request by elky84**

### CODE REVIEW

**Comment by marians** [comment]
@elky84 Thanks for the PR! Can you provide some description regarding what problem it's intended to solve, including a link to the description for sentinel? I haven't heard of it so far.

**Comment by elky84** [comment]
@marians my develop environment always use password. (&sentinel) so i add features. 
this work do always pass parameter (password & sentinel).
I don't know if it is correct. (method of approach)
but i require this feature.
review please. (if possible, want solution more better this.)

**Comment by earthgecko** [comment]
@elky84 as per my comments in https://github.com/marians/rebrow/issues/16#issuecomment-393530526 although this PR works, it is **very bad** to have the password in plaintext URL parameter.
I have ported this to the version of rebrow I use, but I replaced the password URL with an expiring, encoded JWT token and client token unfortunately my use case does not suit rebrow in general so this token functionality modification would not suit PR #20 as it stands as my rebrow implementation is actually storing the encoded JWT token (PyJWT) in Redis itself.

It may be possible to port to the tokens be managed by Flask session, but that also means that really the POST should to be done to a SSL encrypted endpoint, which is outside the scope of rebrow as it stands now.  Unless @marians wants make rebrow more than just a localhost ONLY application, which people do seem be doing with it.

token

**Comment by earthgecko** [comment]
I do not have much time to port my JWT token method to rebrow, however if anyone is interested it attempting to do it and handle it via Flask session or some internal Python method, here is the gist of the basic functionality and some thoughts.

https://gist.github.com/earthgecko/2e395f946cb6039ae476a62bd4c88d38

**Comment by elky84** [comment]
@earthgecko 
i agree your suggest.
change code from your idea.
thanks regard.

**Comment by elky84** [comment]
@marians can u review?
if u possible, merge please. or else review message.

**Comment by marians** [comment]
@elky84 I have no setup available to test this with. Can you provide some simple instructions to set one up, ideally as a `docker-compose.yaml` file?

Looking at the screenshot above, a few things come to my mind:

image

- why is the text underneath input fields offset to the left? Input field and text should be left-aligned to the same axis.
- For the password field: I'd like us to indicate that this might not be required, depending on the redis setup. So a help line would be nice, saying `If unsure, leave blank` or something along these lines.
- token valid for - what is this? Is it necessary to show this to every user on every login?

**Pull request closed without merging**
